# Generated by Django 5.0.6 on 2024-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('L', 'Loisir'), ('J', 'Jeunes'), ('C', 'Compétiteurs')], default='C', max_length=100),
        ),
    ]
