# Generated by Django 4.2.13 on 2024-07-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_type_tournament_category_tournament_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='set_number',
        ),
    ]
