# Generated by Django 4.2.13 on 2024-07-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0002_alter_player_tournaments'),
        ('tournament', '0003_rename_type_tournament_category_tournament_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreboardPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboards', to='player.player')),
                ('scoreboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard_players', to='scoreboard.scoreboard')),
            ],
        ),
    ]
