# Generated by Django 5.0.6 on 2024-06-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0002_tournament_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('tournaments', models.ManyToManyField(to='tournament.tournament')),
            ],
        ),
    ]
