# Generated by Django 5.0.6 on 2024-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('tournament', '0002_tournament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(related_name='players', to='tournament.tournament'),
        ),
    ]
