# Generated by Django 4.2.13 on 2024-06-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_tournaments'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepPLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='player.player')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='step.step')),
            ],
        ),
    ]
