# Generated by Django 4.2.13 on 2024-06-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_tournaments'),
        ('step', '0002_stepplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepPLayers',
            new_name='StepPLayer',
        ),
    ]
