# Generated by Django 4.2.13 on 2024-06-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_rename_stepplayers_stepplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='last_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.step'),
        ),
    ]
