# Generated by Django 4.2.13 on 2024-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_step_last_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepplayer',
            name='coeff',
            field=models.FloatField(default=0),
        ),
    ]
