# Generated by Django 4.2.13 on 2024-06-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_tournaments'),
        ('step', '0005_stepplayer_coeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='players',
            field=models.ManyToManyField(related_name='steps', to='player.player'),
        ),
        migrations.DeleteModel(
            name='StepPLayer',
        ),
    ]
