# Generated by Django 4.2.13 on 2024-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_step_players_delete_stepplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
