# Generated by Django 4.2.13 on 2024-07-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_step_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
    ]
