# Generated by Django 5.0.6 on 2024-06-05 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0002_alter_player_tournaments'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='pools', to='game.game')),
                ('players', models.ManyToManyField(related_name='pools', to='player.player')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.step')),
            ],
        ),
    ]
