# Generated by Django 4.2.13 on 2024-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
