# Generated by Django 4.2.13 on 2024-06-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_tournaments'),
        ('pool', '0002_pool_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='players',
        ),
        migrations.CreateModel(
            name='PoolPLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('coeff', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='player.player')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pool.pool')),
            ],
        ),
    ]
