# Generated by Django 4.2.13 on 2024-06-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_step_rank'),
        ('pool', '0003_remove_pool_players_poolplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='step.step'),
        ),
    ]
