# Generated by Django 4.2.13 on 2024-07-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_alter_pool_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='games',
        ),
    ]
