# Generated by Django 4.2.13 on 2024-07-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_remove_pool_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='validated',
        ),
    ]
