# Generated by Django 4.2.13 on 2024-08-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_remove_pool_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='table',
            field=models.IntegerField(null=True),
        ),
    ]
